# Generated by Django 4.2.1 on 2023-05-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpairs',
            name='user',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
